export const FETCH_CHAMPIONS_START = "FETCH_CHAMPIONS"
export const FETCH_CHAMPIONS_SUCCESS = "FETCH_CHAMPIONS_SUCCESS"
export const FETCH_CHAMPIONS_FAILED = "FETCH_CHAMPIONS_FAILED"

export const FETCH_SINGLE_CHAMP_START = "FETCH_SINGLE_CHAMP_START"
export const FETCH_SINGLE_CHAMP_SUCCESS = "FETCH_SINGLE_CHAMP_SUCCESS"
export const FETCH_SINGLE_CHAMP_FAILED = "FETCH_SINGLE_CHAMP_FAILED"

export const FETCH_SINGLE_CHAMP_DATA_START = "FETCH_SINGLE_CHAMP_DATA_START"
export const FETCH_SINGLE_CHAMP_DATA_SUCCESS = "FETCH_SINGLE_CHAMP_DATA_SUCCESS"
export const FETCH_SINGLE_CHAMP_DATA_FAILED = "FETCH_SINGLE_CHAMP_DATA_FAILED"

export const CHAMPIONS_IMAGE_FETCH = "CHAMPIONS_IMAGE_FETCH"
export const CHAMPIONS_EDIT = "FETCH_CHAMPIONS_EDIT"
export const CHAMPIONS_EDIT_CONFIRM = "CHAMPIONS_EDIT_CONFIRM"
export const CHAMPIONS_DELETE = "FETCH_CHAMPIONS_DELETE"
export const CHAMPIONS_ADD = "FETCH_CHAMPIONS_ADD"

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
