export const FETCH_SINGLE_CHAMP = "FETCH_SINGLE_CHAMP"
export const ADD_CHAMPION = "ADD_CHAMPION"
export const DELETE_CHAMPION = "DELETE_CHAMPION"
export const EDIT_CHAMPION = "EDIT_CHAMPION"

export const FETCH_CHAMPIONS_START = "FETCH_CHAMPIONS"
export const FETCH_CHAMPIONS_SUCCESS = "FETCH_CHAMPIONS_SUCCESS"
export const FETCH_CHAMPIONS_FAILED = "FETCH_CHAMPIONS_FAILED"
