export const FETCH_CHAMPIONS_START = "FETCH_CHAMPIONS"
export const FETCH_CHAMPIONS_SUCCESS = "FETCH_CHAMPIONS_SUCCESS"
export const FETCH_CHAMPIONS_FAILED = "FETCH_CHAMPIONS_FAILED"

export const FETCH_CHAMPIONS_EDIT = "FETCH_CHAMPIONS_EDIT" 
export const FETCH_CHAMPIONS_DELETE = "FETCH_CHAMPIONS_DELETE"
export const FETCH_CHAMPIONS_ADD = "FETCH_CHAMPIONS_ADD"

